#! base.yaml
application:
  port: 8000
  hmac_secret: "Ba5UbwF1zfM7dsH7VzwGKyzHRd5TFYbjNUubddFEZgqHQWn3NmsxKXp8CDmR3V2C"

database:
  host: "127.0.0.1"
  port: 2343
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: "127.0.0.1"
  sender_email: "test@gmail.com"
  auth_token: "secret-token"
  timeout_milliseconds: 10000

redis_uri: "redis://127.0.0.1:6379"
