name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Code Coverage
      run: cargo tarpaulin --ignore-tests
    - name: Run Linter
      run: cargo clippy -- -D warnings
    - name: Run Formatter
      run: cargo fmt -- --check
    - name: Check Vulnerabilities
      run: cargo audit
